title: Doruk Alkan
favicon: favicon.ico
logo: assets/img/notion-avatar-1739440089331.png

description: |
  <p><strong>Technical Skills</strong></p>
  <ul>
    SQL (Postgres, MySQL, SQL Server)
    Python (Pandas, NumPy, Matplotlib, Seaborn)
    BI &amp; Visualization (Power BI, Tableau, Excel)
  </ul>

  <p><strong>Education</strong></p>
  <p>B.A., Linguistics @ Boğaziçi University (<em>February 2025</em>)</p>

  <p><a href="mailto:dorukalkan1.0@gmail.com">Contact Me via E-mail</a></p>
  <p><a href="https://www.linkedin.com/in/doruk-alkan/">View My LinkedIn Profile</a></p>

theme: jekyll-theme-minimal
