title: Doruk Alkan
favicon: favicon.ico
logo: assets/img/notion-avatar-1739440089331.png

description: |
  <p><strong>Technical Skills</strong></p>
  <ul style="margin-left: 0; padding-left: 0;">
    <li>SQL (Postgres, MySQL, SQL Server)</li>
    <li>Python (Pandas, NumPy, Matplotlib, Seaborn)</li>
    <li>BI &amp; Visualization (Power BI, Tableau, Excel)</li>
  </ul>

  <p><strong>Education</strong></p>
  <p>B.A., Linguistics @ Boğaziçi University (<em>February 2025</em>)</p>

  <p style="margin-bottom: 0;">
    <a href="mailto:dorukalkan1.0@gmail.com">Contact Me via E-Mail</a><br>
    <a href="https://www.linkedin.com/in/doruk-alkan/">View My LinkedIn Profile</a>
  </p>

theme: jekyll-theme-minimal
