title: Doruk Alkan
favicon: assets/img/favicon.ico
logo: assets/img/image.png

description: |
  <p><strong>Skills</strong></p>
  <ul style="list-style: none; margin-left: 0; padding-left: 0;">
    <li>SQL | Postgres, MySQL, SQL Server</li>
    <li>Python | Pandas, NumPy, Matplotlib, Seaborn</li>
    <li>BI &amp; Visualization | Power BI, Tableau, Excel</li>
  </ul>

  <p><strong>Education</strong></p>
  <p>B.A., Linguistics @ Boğaziçi University (<em>February 2025</em>)</p>

theme: jekyll-theme-minimal
