[project]
site_name = "doruk docs"
site_url = "https://docs.dorukalkan.com"
site_description = "Personal technical notes, references, and project documentation."
site_author = "Doruk Alkan"
docs_dir = "docs"
site_dir = "site"

[project.theme]
logo = "assets/images/logo.png"
favicon = "assets/images/favicon.ico"
